"""BaselineSchema

Revision ID: b2ae11e9d9c6
Revises: 
Create Date: 2026-03-03 10:54:32.799241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2ae11e9d9c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opp_score_section_value')
    op.drop_constraint(op.f('app_user_email_key'), 'app_user', type_='unique')
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.add_column('opp_score_section', sa.Column('reasons', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_opp_score_values_score_version_id'), 'opp_score_values', ['score_version_id'], unique=False)
    op.create_index(op.f('ix_opp_score_values_section_code'), 'opp_score_values', ['section_code'], unique=False)
    op.alter_column('opp_score_version', 'created_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('unique_opp_version', 'opp_score_version', ['opp_id', 'version_no'])
    op.create_index(op.f('ix_opportunity_opp_number'), 'opportunity', ['opp_number'], unique=False)
    op.create_index(op.f('ix_opportunity_workflow_status'), 'opportunity', ['workflow_status'], unique=False)
    op.create_foreign_key(None, 'opportunity', 'app_user', ['assigned_sales_head_id'], ['user_id'])
    op.create_foreign_key(None, 'opportunity', 'app_user', ['assigned_sp_id'], ['user_id'])
    op.create_foreign_key(None, 'opportunity', 'app_user', ['assigned_sa_id'], ['user_id'])
    op.create_foreign_key(None, 'opportunity', 'app_user', ['assigned_practice_head_id'], ['user_id'])
    op.create_index(op.f('ix_opportunity_assignment_assigned_to_user_id'), 'opportunity_assignment', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_opportunity_assignment_opp_id'), 'opportunity_assignment', ['opp_id'], unique=False)
    op.drop_constraint(op.f('practice_practice_head_user_id_fkey'), 'practice', type_='foreignkey')
    op.drop_column('practice', 'practice_head_user_id')
    op.drop_column('sync_run', 'last_success_cutoff')
    op.drop_column('sync_run', 'source_system')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_run', sa.Column('source_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sync_run', sa.Column('last_success_cutoff', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('practice', sa.Column('practice_head_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('practice_practice_head_user_id_fkey'), 'practice', 'app_user', ['practice_head_user_id'], ['user_id'])
    op.drop_index(op.f('ix_opportunity_assignment_opp_id'), table_name='opportunity_assignment')
    op.drop_index(op.f('ix_opportunity_assignment_assigned_to_user_id'), table_name='opportunity_assignment')
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_workflow_status'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_opp_number'), table_name='opportunity')
    op.drop_constraint('unique_opp_version', 'opp_score_version', type_='unique')
    op.alter_column('opp_score_version', 'created_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_opp_score_values_section_code'), table_name='opp_score_values')
    op.drop_index(op.f('ix_opp_score_values_score_version_id'), table_name='opp_score_values')
    op.drop_column('opp_score_section', 'reasons')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.create_unique_constraint(op.f('app_user_email_key'), 'app_user', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table('opp_score_section_value',
    sa.Column('score_value_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score_version_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('section_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['score_version_id'], ['opp_score_version.score_version_id'], name=op.f('opp_score_section_value_score_version_id_fkey')),
    sa.ForeignKeyConstraint(['section_code'], ['opp_score_section.section_code'], name=op.f('opp_score_section_value_section_code_fkey')),
    sa.PrimaryKeyConstraint('score_value_id', name=op.f('opp_score_section_value_pkey'))
    )
    # ### end Alembic commands ###
