"""Add MVP columns

Revision ID: f7f1087a2ff8
Revises: f5e1a2b3c4d5
Create Date: 2026-03-11 12:22:23.625435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f1087a2ff8'
down_revision: Union[str, Sequence[str], None] = 'f5e1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minimal_opportunities')
    op.drop_table('sync_state')
    op.add_column('opportunity', sa.Column('margin_percentage', sa.Float(), nullable=True))
    op.add_column('opportunity', sa.Column('bid_manager_user_id', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('finance_approval_status', sa.String(), nullable=True))
    op.add_column('opportunity', sa.Column('legal_approval_status', sa.String(), nullable=True))
    op.execute("UPDATE opportunity SET deal_value = 0.0 WHERE deal_value IS NULL")
    op.alter_column('opportunity', 'deal_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.execute("UPDATE opportunity SET stage = 'Lead' WHERE stage IS NULL")
    op.alter_column('opportunity', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE opportunity SET workflow_status = 'UNDER_ASSESSMENT' WHERE workflow_status IS NULL")
    op.alter_column('opportunity', 'workflow_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'opportunity', 'app_user', ['bid_manager_user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity', type_='foreignkey')
    op.alter_column('opportunity', 'workflow_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opportunity', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opportunity', 'deal_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('opportunity', 'legal_approval_status')
    op.drop_column('opportunity', 'finance_approval_status')
    op.drop_column('opportunity', 'bid_manager_user_id')
    op.drop_column('opportunity', 'margin_percentage')
    op.create_table('sync_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_synced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_state_pkey')),
    sa.UniqueConstraint('sync_name', name=op.f('sync_state_sync_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('minimal_opportunities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('opportunity_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('minimal_opportunities_pkey')),
    sa.UniqueConstraint('opportunity_id', name=op.f('minimal_opportunities_opportunity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
